## numpy 브로드 캐스팅 실습


### Fizz Buzz 문제
- 100~130까지 랜덤한 숫자를 가지는 8*8행렬을 만들고
- 3의 배수는 fiz, 5의 배수는 buz, 3,5의 배수는 fbz 문자로 변환

In [7]:
import numpy as np
import random
datas= np.random.randint(100,131,size=(8,8))
datas

array([[117, 102, 121, 123, 117, 116, 127, 106],
       [120, 124, 116, 127, 112, 128, 106, 100],
       [127, 107, 102, 109, 124, 125, 117, 116],
       [107, 125, 125, 120, 118, 116, 122, 101],
       [106, 111, 101, 102, 124, 104, 114, 122],
       [107, 110, 107, 111, 112, 123, 114, 129],
       [111, 111, 105, 121, 128, 108, 114, 116],
       [113, 103, 124, 125, 112, 115, 106, 119]])

In [21]:
idx_03=datas%3==0
idx_05=datas%5==0
idx_15=(datas%3==0) & (datas%5)==0

In [22]:
datas_str=datas.astype('str')

In [23]:
datas_str[idx_03]="fiz"
datas_str[idx_05]="buz"
datas_str[idx_15]="fbz"
datas_str


array([['fbz', 'fbz', 'fbz', 'fiz', 'fbz', 'fbz', 'fbz', 'fbz'],
       ['fbz', 'fbz', 'fbz', 'fbz', 'fbz', 'fbz', 'fbz', 'fbz'],
       ['fbz', 'fbz', 'fbz', 'fbz', 'fbz', 'fbz', 'fbz', 'fbz'],
       ['fbz', 'fbz', 'fbz', 'fbz', 'fbz', 'fbz', 'fbz', 'fbz'],
       ['fbz', 'fiz', 'fbz', 'fbz', 'fbz', 'fbz', 'fbz', 'fbz'],
       ['fbz', 'fbz', 'fbz', 'fiz', 'fbz', 'fiz', 'fbz', 'fbz'],
       ['fiz', 'fiz', 'fbz', 'fbz', 'fbz', 'fiz', 'fbz', 'fbz'],
       ['fbz', 'fbz', 'fbz', 'fbz', 'fbz', 'fbz', 'fbz', 'fbz']],
      dtype='<U11')

### quiz
- 1~20까지 랜덤한 숫자를 가지는 5*5 행렬 생성
- 최대값에는 MAX, 최소값에는 MIN문자열이 들어가도록 치환하는 코드 작성
- 최대값과 최소값 함수
```
np.min(ndarray), np.max(ndarray)
```

In [22]:
datas=np.random.randint(1,21,(5,5))
datas

array([[ 4, 19, 11, 15,  4],
       [ 6, 15, 16,  5,  7],
       [14, 18, 15, 15, 12],
       [11, 15, 14, 20, 15],
       [ 3, 12, 18,  3,  9]])

In [23]:
min_num = np.min(datas)
max_num = np.max(datas)

In [24]:
idx_min_num=datas==min_num
idx_max_num=datas==max_num
#idx_min_num


In [25]:
result=datas.astype('str')

In [29]:
result[idx_min_num]='min'
result


array([['4', '19', '11', '15', '4'],
       ['6', '15', '16', '5', '7'],
       ['14', '18', '15', '15', '12'],
       ['11', '15', '14', '20', '15'],
       ['min', '12', '18', 'min', '9']], dtype='<U11')

In [30]:
result[idx_max_num]='max'
result

array([['4', '19', '11', '15', '4'],
       ['6', '15', '16', '5', '7'],
       ['14', '18', '15', '15', '12'],
       ['11', '15', '14', 'max', '15'],
       ['min', '12', '18', 'min', '9']], dtype='<U11')

In [ ]:
### linspace, logspace 함수
- linspace:설정한 범위에서 선형적으로 분할한 위치의 값을 출력
- logspace: 설정한 범위에서 로그로 분할한 위치의 값을 출력 

In [31]:
#linspace
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [32]:
#logspace
np.logspace(2,4,3)

array([  100.,  1000., 10000.])

In [34]:
### 30세에 연봉이 $100000이고 60세의 연봉이 $1000000일때
#연봉이 선형으로 증가. 지수함수로 증가하는 두 경우에서 40, 50세 연봉을 출력

In [35]:
#linspace
age_30=100000
age_60=1000000

np.linspace(age_30,age_60,4)

array([ 100000.,  400000.,  700000., 1000000.])

In [38]:
#logspace
np.logspace(np.log10(age_30), np.log10(age_60),4)

array([ 100000.        ,  215443.46900319,  464158.88336128,
       1000000.        ])

### numpy random

In [39]:
#seed : 랜덤값의 설정값
np. random.seed(1)
result1= np.random.randint(10,101,10)

np. random.seed(2)
result2= np.random.randint(10,101,10)

np. random.seed(1)
result3= np.random.randint(10,101,10)

result1, result2, result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]))

In [45]:
#rand: 군등분포로 난수생성
np.random.rand(10)


array([0.98907569, 0.31845712, 0.02390378, 0.80856415, 0.97325255,
       0.73758851, 0.00273581, 0.06336051, 0.58426941, 0.33571511])

In [46]:
#randn: 정규분포로 난수를 발생
np.random.randn(10)

array([-0.36583665,  0.76450212, -0.70262028, -1.71176487,  1.18113873,
        1.64113619, -1.86053074, -1.29227662,  0.09417316, -1.04936032])

In [50]:
#shuffle: 행렬 데이터 섞어주기
data=np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
np.random.shuffle(data)
data

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [76]:
#choice: 특정확률로 데이터를 선택
a=np.random.choice(5,10,p=[0.1,0,0.4,0.2,0.3])
a

array([3, 2, 3, 4, 4, 4, 3, 2, 2, 4], dtype=int64)

In [80]:
#unique: 배열 내 중복된 원소 제거 후 유일한 원소를 정렬하여 반환
numbers, counts= np.unique(a, return_counts=True)
print(numbers)
print(counts)

[2 3 4]
[3 3 4]


### 행렬데이터의 결합

In [81]:
na1= np.random.randint(10, size=(4,3))
na2= np.random.randint(10, size=(3,4))
na3= np.random.randint(10, size=(3,3))


In [82]:
na1

array([[9, 7, 8],
       [4, 9, 9],
       [4, 2, 9],
       [0, 4, 5]])

In [83]:
na2

array([[6, 9, 9, 2],
       [0, 6, 3, 1],
       [1, 1, 2, 6]])

In [84]:
na3

array([[9, 2, 0],
       [5, 4, 0],
       [3, 7, 6]])

In [85]:
#세로결합
np.concatenate((na1,na3))

array([[9, 7, 8],
       [4, 9, 9],
       [4, 2, 9],
       [0, 4, 5],
       [9, 2, 0],
       [5, 4, 0],
       [3, 7, 6]])

In [90]:
#가로결합
np.concatenate((na2,na3), axis=1)

array([[6, 9, 9, 2, 9, 2, 0],
       [0, 6, 3, 1, 5, 4, 0],
       [1, 1, 2, 6, 3, 7, 6]])

In [101]:
#c_ 또는 #r_로 결합하기
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [106]:
np.c_[na3,na3]

array([[9, 2, 0, 9, 2, 0],
       [5, 4, 0, 5, 4, 0],
       [3, 7, 6, 3, 7, 6]])

In [108]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [113]:
np.r_[na1, na3]

array([[9, 7, 8],
       [4, 9, 9],
       [4, 2, 9],
       [0, 4, 5],
       [9, 2, 0],
       [5, 4, 0],
       [3, 7, 6]])