In [13]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [14]:
array.ndim

1

In [15]:
array.shape

(12,)

In [20]:
array=array.reshape(3,2,2)

In [21]:
array

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [25]:
array[0,1]

array([3, 4])

In [33]:
array[0:2][-1:]

array([[[5, 6],
        [7, 8]]])

In [34]:
array[0][1]=4

In [35]:
array

array([[[ 1,  2],
        [ 4,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [38]:
array[0][0][1]=1

In [39]:
array

array([[[ 1,  1],
        [ 4,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [40]:
idx= array>4

In [43]:
array[idx]=100


In [46]:
array

array([[[  1,   1],
        [  4,   4]],

       [[100, 100],
        [100, 100]],

       [[100, 100],
        [100, 100]]])

In [60]:
array2=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array2=array2.reshape(3,2,2)

In [58]:
array2= array[idx]

In [59]:
array2

array([100, 100, 100, 100, 100])

In [51]:
idx=array2>7

In [52]:
idx

array([[[False, False],
        [False, False]],

       [[False, False],
        [False,  True]],

       [[ True,  True],
        [ True,  True]]])

In [53]:
array3=array2[idx]

In [54]:
array3

array([ 8,  9, 10, 11, 12])

In [55]:
array3

array([ 8,  9, 10, 11, 12])

In [56]:
array3

array([ 8,  9, 10, 11, 12])

In [61]:
array2[idx]

array([ 8,  9, 10, 11, 12])

In [62]:
array2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [73]:
data=np.zeros((3))

In [74]:
data


array([0., 0., 0.])

In [81]:
array2=np.array([1,2,3,4,5,6])

In [82]:
array2=array2.reshape(2,3)

In [83]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
mul=np.zeros((3,2))

In [86]:
mul

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [97]:
mul=mul.astype('int')

In [98]:
mul.dtype

dtype('int32')

In [115]:
mul

array([[0, 0],
       [0, 0],
       [0, 0]])

In [117]:
array2[0]=1,2,3


In [120]:
array2*[0,1,2]

array([[ 0,  2,  6],
       [ 0,  2, 10]])

In [92]:
array2[0]=0

In [93]:
array2

array([[0, 0, 0],
       [4, 5, 6]])

In [94]:
array2[1]=[3,2,5]

In [95]:
array2

array([[0, 0, 0],
       [3, 2, 5]])

In [100]:
data=np.arange(5)

In [101]:
data

array([0, 1, 2, 3, 4])

In [108]:
data=np.arange(6).reshape(3,2)

In [109]:
data

array([[0, 1],
       [2, 3],
       [4, 5]])

In [110]:
data1 = np.array([80, 85, 100, 90, 95])
data2 = np.array([70, 80, 100, 95, 95])

In [111]:
np.var(data1)

50.0

In [125]:
np.std(data1)

7.0710678118654755

In [114]:
np.cov(data1, data2)[0,1]

93.75

In [151]:
# 상관계수 (공분산/std(data1)* std(data2))
(np.corrcoef(data1,data2)[0,1])

0.9449111825230682

In [142]:
np.cov(data1,data2)[0,1]/(np.std(data1)*np.std(data2))

1.181138978153835

In [143]:
93.75/(np.std(data1)*np.std(data2))

1.181138978153835