- 두개의 리스트 A, B가 있다.
- 리스트의 원소는 정수라고 가정하고, 리스트 A, B의 크기(원소의 개수)는 m, n 이다. 
- p, q 가 각각 리스트 A, B의 하나의 원소라고 하면, p와 q의 값의 차이(절대값)가 가장 큰 쌍과 가장 작은 쌍을 찾으시오. 
- 예를 들어,A=[2, -1, 5], B=[-3, 2, 4, 1, 5] 이면, 가장 큰 쌍은 (5, -3)이고 가장 작은 쌍은 (2, 2) 이다. 일반적인 m,n에 대해 프로그램이 작동되어야 하고, A, B는 프로그램 내에 있는 것으로 하여 별도의 입력 프로그램 코드가 필요하지 않다.

In [10]:
a=np.array([[2],[-1],[5]])
b=np.array([[-3],[2],[4],[1],[5]])

result=a.T-b

print(abs(result))



[[5 2 8]
 [0 3 3]
 [2 5 1]
 [1 2 4]
 [3 6 0]]


In [13]:
idx=np.where(result==np.amax(abs(result)))
y=int(idx[0])
x=int(idx[1])

print("최댓값의 조합")

        
result_arr= np.c_[x,y]

for x1,x2 in result_arr:
    x_a=a[x1]
    x_b=b[x2]
    print("(",x_a,",",x_b,")")
print("그때의 결과값은 {}".format(np.amax(abs(result))))



최댓값의 조합
( [5] , [-3] )
그때의 결과값은 8


In [16]:
print("최소값의 조합")
    
idx2=np.where(result==np.amin(abs(result)))
y=idx2[0]
x=idx2[1]

result_arr= np.c_[x,y]
for x1,x2 in result_arr:
    x_a=a[x1]
    x_b=b[x2]
    print("(",x_a,",",x_b,")")
print("그때의 결과값은 {}".format(np.amin(abs(result))  ))

최소값의 조합
( [2] , [2] )
( [5] , [5] )
그때의 결과값은 0


In [ ]:
#앞으로 풀 문제

In [ ]:
- 프로그램 내에 2차원 행렬 A가 있다. 
- 별도의 입력 프로그램 코드가 필요하지 않다. 
- 행렬은 n x n 크기이다. 
- 행렬 내의 각 원소의 값은 자연수라고 가정하고, 임의의 값을 부여한다. 
- 부분행렬은 (1,1)부터 (k,k) 로 정의된다. 즉, (1,1)에서부터 생성할 수 있는 정방행렬(square matrix)로 정의된다.
- part_sum 이라는 함수는 파라미터 k에 대해 (1,1)부터 (k,k)까지의 모든 원소들의 합을 계산하여 return 하는 함수이다. 
- 예를 들어,일 때, k=2 이면, 의 각 원소들의 합 14를 return 하게 된다.
- 주 프로그램에서는 A의 각 부분행렬들의 원소들의 합을 part_sum을 호출하여 k=1부터 n까지 계산한다. 
- 위 예에서는 5, 14, 26을 각각 출력한다. 이러한 기능을 수행하는 주 프로그램과 part_sum 함수를 python으로 작성하라.
- part_sum 은 다양한 행렬의 크기에 대해 작동하여야 하고, 특정 k에 대해 위의 설명과 같이 하나의 부분행렬의 원소들의 합만 계산하여야 한다.

In [3]:
A=np.ones((5,5))
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
k=3
B=A[:k,:k]
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
sum(sum(B))

9.0